from typing import List, Protocol

from core.interfaces.base_item import IMTTreeItem
from platforms.interfaces.collection_view import IMTCollectionView
class IMTTreeView(IMTCollectionView, Protocol):
    def expand_item(self, item_id: str) -> None: ...
    def collapse_item(self, item_id: str) -> None: ...
    def set_tree_data(self, items: List[IMTTreeItem]) -> None: ...
