class TreeItemKeys:
    """트리 아이템 속성 키 상수 정의"""
    ID = "id"
    NAME = "name"
    PARENT_ID = "parent_id"
    CHILDREN = "children"
    DATA = "data"
    TYPE = "type"
    ACTION = "action"
    ACTION_DATA = "action_data"
    EXPANDED = "expanded"
    SELECTED = "selected"
    VISIBLE = "visible"
    ICON = "icon"
