from typing import Protocol

class IMTTreeViewModelModel(Protocol):
    def undo(self) -> bool: ...
    def redo(self) -> bool: ...
    def save_tree(self, tree_id: str | None = None) -> str | None: ...
    def load_tree(self, tree_id: str) -> bool: ...
    # 기타 model 기반 부가 메서드 