from typing import Protocol, List, Any
from temp.platform.interfaces.ui_element import IMTUIElement

class IMTCollectionView(IMTUIElement, Protocol):
    def set_items(self, items: List[Any]) -> None: ...
    def get_selected_items(self) -> List[Any]: ...
    def select_item(self, item_id: str) -> None: ...
