from typing import Protocol, Callable
from model.events.interfaces.base_tree_event_mgr import MTTreeEvent

class IMTTreeViewModelModel(Protocol):
    def undo(self) -> bool: ...
    def redo(self) -> bool: ...
    def save_tree(self, tree_id: str | None = None) -> str | None: ...
    def load_tree(self, tree_id: str) -> bool: ...

    def subscribe(self, event_type: MTTreeEvent, callback: Callable) -> None: ...
    def unsubscribe(self, event_type: MTTreeEvent, callback: Callable) -> None: ...