name: Basic CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # 코드 체크아웃
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8 mypy
          
          # Windows 패키지 제거 후 설치
          sed -i '/pywin32/d; /pypiwin32/d; /pywinpty/d' requirements.txt
          pip install -r requirements.txt
      
      - name: Lint with flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --max-line-length=127
      
      - name: Type check with mypy
        run: mypy .
      
      - name: Test with pytest
        run: pytest
