name: Generate Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**/*.py'
      - 'docs/**'
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdoc
        # 문서 생성에 필요한 최소 의존성만 설치
        pip install typing_extensions dataclasses
    
    - name: Generate API documentation
      run: python generate_docs.py
    
    - name: Upload documentation
      uses: actions/upload-artifact@v4
      with:
        name: api-docs
        path: docs/api/
        
    # 선택사항: GitHub Pages로 배포
    # - name: Deploy to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./docs/api 